### ISSUE TITLE
Exception bij Opstarten User Interface

### ISSUE THREAD

**Issue by oxygenius** [lmeulen/IJC_UI#14]
nov 21, 2016 11:12:58 AM nl.detoren.ijc.IJC_Wedstrijden main
INFO: Opstarten user interface
Exception in thread "main" java.lang.NullPointerException
	at nl.detoren.ijc.ui.view.Hoofdscherm.updateUpdateStandButton(Hoofdscherm.java:280)
	at nl.detoren.ijc.ui.view.Hoofdscherm.initComponents(Hoofdscherm.java:154)
	at nl.detoren.ijc.ui.view.Hoofdscherm.<init>(Hoofdscherm.java:120)
	at nl.detoren.ijc.IJC_Wedstrijden.main(IJC_Wedstrijden.java:51)

**Comment by oxygenius** [comment]
Bugfix: Oude configuratie.json teruggezet (die van github gewist).
